# Generated by Django 2.1.3 on 2018-11-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaInicial',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
    ]
